In [2]:
%load_ext autoreload

In [22]:
%autoreload 2
import cv2
import matplotlib.pyplot as plt
import sys
sys.path.append('/home/dan/Dropbox/Create/ThinAir/CytoDynamic/master')
import image as img
import copy
import numpy as np
import pandas as panda
from waveform import *
import importlib

In [9]:
%matplotlib widget
sig_32 = Waveform(64, "Sig 32 Waveform")
sig_64 = Waveform(64, "Sig 64 Waveform")
sig_32.gen_sinusoid({'form':'cos', 'amp':5, 'f':2},
                    {'form':'cos', 'amp':3, 'f':1},
                    {'form':'cos', 'amp':6, 'f':4})
sig_64.gen_sinusoid({'form':'cos', 'amp':5, 'f':2},
                    {'form':'cos', 'amp':3, 'f':1})
# print(sig_32.n_shift[20])

# print(sig_64.x[sig_32.x[20]])

sig_32.dft()
sig_64.dft()
# sig_32.plot_waveform(sig_32.X_mag_shift, "Sig 32")
# sig_64.plot_waveform(sig_64.X_mag_shift, "Sig 64")
Waveform.plot_norm_fft_comparison(sig_64, sig_32)
plt.show()






-12


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [74]:
%matplotlib widget
array = Waveform_2D(512,256)
df=array.show_matrix()
df

# array.g_xy[1,0] = 255


array.gen_sinusoid_2D(
     {'dim':'y', 'amp':4, 'form':'sin', 'k_y':20},
     {'dim':'x', 'amp':2, 'form':'cos', 'k_x':40})

array.fft2d()
# sine = array.g_xy
# print(array.m)
# print(type(array.m))
# print(array.g_xy[0:3, 0:3])
# df_1 = pd.DataFrame(array.g_xy)
# df_1
array.show_im(array.g_xy, 'G_XY')
array.show_im(array.g_XY_mag_shift, 'X Mag Shifted')


plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [4]:

wave = Waveform_2D(512,256)

wave.gen_sinusoid_2D(
     {'dim':'y', 'amp':4, 'form':'sin', 'k_y':20},
     {'dim':'x', 'amp':2, 'form':'cos', 'k_x':40})

roi = cv2.selectROI(wave.g_xy)

# wave.grab_area()

# roi.show_im(roi.g_xy, 'ROI')


In [5]:
nums = np.zeros((5,6), int)
print(nums)
print(nums.shape)
print(type(nums))

bl = None
print(type(bl))
if bl == None:
    print('Yes')
    
class TestIf():
    def __init__(self, a=None, b=None):
        if not a:
            self.b="chedda"
        else:
            self.b = "tuna"
        
        self.a = a

steez = TestIf()
print(steez.b)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(5, 6)
<class 'numpy.ndarray'>
<class 'NoneType'>
Yes
chedda


In [25]:
# Check X_bar[k] equation
%matplotlib widget
import math
sig_32 = Waveform(32, "Sig 32 Waveform")
sig_64 = Waveform(64, "Sig 64 Waveform")
sig_32.gen_sinusoid({'form':'cos', 'amp':5, 'f':2},
                    {'form':'cos', 'amp':3, 'f':1},
                    {'form':'cos', 'amp':6, 'f':4})

sig_64.gen_sinusoid({'form':'cos', 'amp':5, 'f':2},
                    {'form':'cos', 'amp':3, 'f':1},
                    {'form':'cos', 'amp':6, 'f':4})
# Get DFT, variable of interest is X[k] or sig32.X
sig_32.dft()

# Show signals in discrete format
sig_32.plot_waveform(sig_32.x, "Sig 32")
sig_64.plot_waveform(sig_64.x, "Sig 64")

# Check equation 
X_bar_check = (abs(sig_32.X)*2)/sig_32.N
print(X_bar_check)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[2.72004641e-15 3.00000000e+00 5.00000000e+00 8.76001601e-16
 6.00000000e+00 2.07679085e-15 9.82092519e-16 1.95494639e-15
 2.44312138e-15 1.20920057e-15 7.55033286e-16 2.12066379e-16
 2.25419022e-15 1.47907373e-15 1.14439170e-15 1.15943913e-15
 1.83186799e-15 1.15943913e-15 1.14439170e-15 1.51684831e-15
 2.25419022e-15 1.57811157e-16 7.55033286e-16 1.18571871e-15
 2.44312138e-15 1.93772883e-15 9.82092519e-16 2.10702328e-15
 6.00000000e+00 9.61183291e-16 5.00000000e+00 3.00000000e+00]


In [31]:
# Pad Check

xx = np.arange(25)
n_0 = 10
n_os = 10
xx_1 = xx[ n_0 : ( n_0 + n_os ) ]
xx_pad = np.pad(xx_1, (n_0, len(xx) - (n_0 + n_os)))
print(xx)
print(xx_1)
print(xx_pad)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[10 11 12 13 14 15 16 17 18 19]
[ 0  0  0  0  0  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19  0  0  0  0
  0]


In [47]:
# Pad and Compare FFT
%matplotlib widget
import math

# Create Waveforms
sig_64 = Waveform(512, "Sig 64 Waveform")
sig_64.gen_sinusoid({'form':'cos', 'amp':5, 'f':50},
                    {'form':'cos', 'amp':3, 'f':0},
                    {'form':'cos', 'amp':6, 'f':0})

# Imitate roi selection
roi_0 = 5
roi_os = 200
sig_64_roi = sig_64.x[ roi_0 : roi_0 + roi_os ]

# Pad roi selection
sig_64_roi_pad = np.pad(sig_64_roi, (roi_0 ,len(sig_64.x)-(roi_0+roi_os) ))

# Create Waveform Container
sig_64_sel = Waveform(len(sig_64_roi_pad), "Sig 64 Selection ROI")
sig_64_sel.x = sig_64_roi_pad

sig_64_sel2 = Waveform(len(sig_64_roi), "Sig 64 Short")
sig_64_sel2.x = sig_64_roi
# Plot Waveforms and Compare
sig_64.plot_waveform(sig_64.x, "Sig 64 Normal")
sig_64_sel.plot_waveform(sig_64_sel.x, "Sig 64 Padded")
sig_64_sel2.plot_waveform(sig_64_sel2.x, "Sig 64 Short")
# Get FFTs
sig_64.dft()
sig_64_sel.dft()
sig_64_sel2.dft()

# Plot FFTs
sig_64.plot_waveform_centered(sig_64.X_mag_shift, "Normal")
sig_64_sel.plot_waveform_centered(sig_64_sel.X_mag_shift, "Sliced")
sig_64_sel2.plot_waveform_centered(sig_64_sel2.X_mag_shift, "Short")



[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …