In [1]:
import cv2
import matplotlib.pyplot as plt
import sys
sys.path.append('/home/dan/Dropbox/Create/ThinAir/CytoDynamic/master')
import image as img
import copy
import numpy as np
import pandas as pd
# from waveform import *


In [3]:
%matplotlib widget
im = cv2.imread('RK1.jpg')
im = cv2.cvtColor(im, cv2.COLOR_BGR2YUV)
y, u, v = cv2.split(im)
blur = cv2.GaussianBlur(y,(51,51),0)
trans = cv2.transpose(blur)

edges = cv2.Canny(trans,2,6)
df = pd.DataFrame(data=edges)
df.to_csv('file_name.csv')
plt.figure('y')
plt.imshow(trans, cmap='gray')
plt.figure('Canny')
plt.imshow(edges, cmap='gray')
plt.show()
df

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

0     1     2     3     4     5     6     7     8     9     ...  1526  \
0        0     0     0     0     0     0     0     0   255     0  ...     0   
1        0     0     0     0     0     0     0     0   255     0  ...     0   
2        0     0     0     0     0     0     0     0   255     0  ...     0   
3        0     0     0     0     0     0     0     0   255     0  ...     0   
4        0     0     0     0     0     0     0     0   255     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2043     0     0     0     0     0     0     0     0     0     0  ...     0   
2044     0     0     0     0     0     0     0     0     0     0  ...     0   
2045     0     0     0     0     0     0     0     0     0     0  ...     0   
2046     0     0     0     0     0     0     0     0     0     0  ...     0   
2047     0     0     0     0     0     0     0     0     0     0  ...     0   

      1527  1528  1529  1530  1531  1532  1533  1534  1535  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2043     0     0     0     0   255     0     0     0     0  
2044     0     0     0     0     0     0     0     0     0  
2045     0     0     0     0     0     0     0     0     0  
2046     0     0     0     0     0     0     0     0     0  
2047     0     0     0     0     0     0     0     0     0  

[2048 rows x 1536 columns]

In [5]:
%matplotlib widget
gen_im = img.GenImage(16,16, np.uint8)
gen_im.bw_checkerboard(2)
gen_im.show_im()

f = np.fft.fft2(gen_im.image)
fshift = np.fft.fftshift(f)
magnitude_spectrum = 20*np.log(np.abs(fshift))

print(f)

plt.figure("FFT")
plt.imshow(magnitude_spectrum, cmap='gray', vmin=0,vmax=255)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[32640.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j]
 [    0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j]
 [    0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j]
 [    0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j
      0.    +0.j     0.    +0.j     0.    +0.j     0.    +0.j]
 [  

<ipython-input-5-cf37af616fd3>:8: RuntimeWarning: divide by zero encountered in log
  magnitude_spectrum = 20*np.log(np.abs(fshift))


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
%cd ..
%cd master
cells = img.Image('RK1.jpg',0)
messi = img.Image('messi.jpg',0)
immessi = messi.image
imcell = cells.image
print(cells)
print(type(cells.image))
plt.figure()
plt.imshow(imcell)
plt.show()
print(cells.image)
f = np.fft.fft2(cells.image)
fshift = np.fft.fftshift(f)
magnitude_spectrum = 20*np.log(np.abs(fshift))

plt.figure()
plt.imshow(magnitude_spectrum, cmap='gray')


/home/dan/Dropbox/Create/ThinAir/CytoDynamic
/home/dan/Dropbox/Create/ThinAir/CytoDynamic/master
<class 'numpy.ndarray'>


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[ 54  48  44 ... 155 156 167]
 [ 43  39  40 ... 131 129 132]
 [ 35  37  46 ... 114 112 109]
 ...
 [113 105  94 ... 106 103 102]
 [100  96  88 ... 110 108 106]
 [ 92  95  90 ... 116 114 111]]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …